build:
  version: "2.0"

cards:
  message: "Welcome to Lvgod cards related qa APIs "
  contactDetails:
    name: "Bernard Bouwer - developer"
    email: "bernard.bouwer@lvgod.nl"
  onCallSupport:
    - (0032) 419-311-3477
    - (0032) 419-311-3488