build:
  version: "1.0"

loans:
  message: "Welcome to Lvgod loans releated products APIs"
  contactDetails:
    name: "Sanny Panny - Product Manager"
    email: "sanny.panny@lvgod.nl"
  onCallSupport:
    - (0031) 321-456-7890
    - (0031) 321-456-7891